from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class RequestLog(db.Model):
    __tablename__ = 'request_log'
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    client_ip = db.Column(db.String(50))
    method = db.Column(db.String(10))
    path = db.Column(db.String(500))
    query = db.Column(db.String(1000))
    body = db.Column(db.Text)
    status_code = db.Column(db.Integer)
    response_time_ms = db.Column(db.Float)
    request_size = db.Column(db.Integer)
    
    # ML Classification Results
    classification = db.Column(db.String(20)) # 'BENIGN' or 'ATTACK'
    attack_probability = db.Column(db.Float)
    
    # Track if this was generated by our synthetic traffic generator
    is_synthetic = db.Column(db.Boolean, default=False)

class TrafficWindow(db.Model):
    __tablename__ = 'traffic_window'
    id = db.Column(db.Integer, primary_key=True)
    start_time = db.Column(db.DateTime, index=True)
    end_time = db.Column(db.DateTime)
    
    # Extracted behavioral features
    requests_per_window = db.Column(db.Float)
    requests_per_second = db.Column(db.Float)
    unique_client_count = db.Column(db.Float)
    requests_per_client_avg = db.Column(db.Float)
    repeated_request_ratio = db.Column(db.Float)
    endpoint_diversity = db.Column(db.Float)
    avg_inter_request_time = db.Column(db.Float)
    traffic_bytes = db.Column(db.Float)
    avg_request_size = db.Column(db.Float)
    avg_response_time = db.Column(db.Float)
    error_4xx_ratio = db.Column(db.Float)
    error_5xx_ratio = db.Column(db.Float)
    
    # ML Anomaly Results
    status = db.Column(db.String(20)) # 'NORMAL' or 'ANOMALY'
    anomaly_score = db.Column(db.Float)
    
    # Final combined risk evaluated by Risk Engine
    risk_level = db.Column(db.String(20)) # 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'

class Alert(db.Model):
    __tablename__ = 'alert'
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    alert_type = db.Column(db.String(50)) # e.g., 'SQLI_DETECTED', 'BURST_TRAFFIC'
    risk_level = db.Column(db.String(20))
    description = db.Column(db.Text)
    is_resolved = db.Column(db.Boolean, default=False)

class AdminUser(db.Model):
    __tablename__ = 'admin_user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(200), nullable=False)
